/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kijowski

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*
import org.junit.Test
import kotlin.test.assertEquals

class HomeRoutesTest {
    @Test
    fun testGetHome() = testApplication {
        val response = client.get("/")
        assertEquals("hello", response.bodyAsText())
        assertEquals(HttpStatusCode.OK, response.status)
    }
}
