/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kijowski

import io.kijowski.plugins.configureMetrics
import io.kijowski.plugins.configureRouting
import io.kijowski.plugins.configureSerialization
import io.ktor.server.application.*
import io.ktor.server.plugins.callloging.*

fun main(args: Array<String>) = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    install(CallLogging)
    configureSerialization()
    configureMetrics()
    configureRouting()
}
